# action.yaml
name: Convert Jupyter Notebooks to Databricks Notebooks
author: https://www.github.com/rafaelvp-db
icon: book
color: gray-dark
description: |
  Simple action that converts Jupyter .ipynb files into
  Databricks Python notebooks (.py)
inputs:
  inputPath:
    description: 'Relative path to the folder containing Jupyter notebooks'
    required: true
  outputPath:
    description: 'Relative path to the folder to which DB notebooks will be output'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.7'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Convert Jupyter Notebooks to Databricks format
      id: get-square
      run: |
        python src/bryckster.py
          --input_path ${{ inputs.inputPath }}
          --output_path ${{ inputs.outputPath }}
      shell: bash